name: ppob_mpay1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  sizer: 2.0.15
  get_storage: 2.1.1
  internet_connection_checker: 1.0.0+1
  dio: 5.3.3
  wc_form_validators: 1.0.0
  image_picker: 1.0.4
  timer_count_down: 2.2.2
  material_dialogs: 1.1.4
  numeric_keyboard: 1.1.0
  pin_code_fields: 8.0.1
  sms_autofill: 2.3.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: 2.0.9
  getwidget: 4.0.0
  flutter_switch: 0.3.2
  contacts_service: 0.6.3
  permission_handler: 11.0.1
  flutter_screenutil: 5.9.0
  fast_contacts: 3.0.3
  flutter_contacts: 1.1.7+1
  url_launcher: 6.2.1
  fluttercontactpicker: 4.7.0
  another_flushbar: 1.12.30
  intl: 0.18.1
  line_icons: 2.0.3
  bottom_sheet: 4.0.0
  showcaseview: 2.0.3
  screenshot: 2.1.0
  image_gallery_saver: 2.0.3
  esys_flutter_share_plus: 2.2.0
  custom_navigation_bar: 0.8.2
  flutter_dotenv: 5.1.0
  shared_preferences: 2.2.2
  flutter_windowmanager: 0.2.0
  lottie: 2.7.0
  remixicon: 1.0.0
  modal_bottom_sheet: 2.1.2
  google_fonts: 6.1.0
  font_awesome_flutter: 10.6.0
  carousel_slider: 4.2.1
  package_info_plus: 4.2.0
  dropdown_button2: 2.3.9
  clipboard: 0.1.3
  flutter_masked_text2: 0.9.1
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"

flutter: 
  assets: 
    - assets/images/
    - assets/json/
    - assets/
    - .env
  uses-material-design: true

